version: '3.8'

services:

  # react
  frontend:
    image: deukr/feelm-frontend:latest
    container_name: feelm-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - feelm-network

  # spring boot
  backend:
    image: deukr/feelm-backend:latest
    container_name: feelm-backend
    ports:
      - "8080:8080"
#    depends_on:
#      - batch-service
#      - db # DB가 켜져야 백엔드도 켜짐 db랑 batch는 각각 RDS, LAMBDA로 갔으니 제외
    env_file: # .env 파일의 값 가져오기
      - .env
#    environment: 위에 .env파일을 넣고 있으므로 불필요
#      - SPRING_PROFILES_ACTIVE=prod
#      - TZ=Asia/Seoul  # 한국 시간 설정
#      # DB 연결 설정 (Spring이 이 변수를 읽어야 함)
##      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/feelm?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#      - SPRING_DATASOURCE_URL=jdbc:mysql://${RDS_ENDPOINT}:3306/feelm?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#      - SPRING_DATASOURCE_USERNAME=root # RDS_USERNAME를 root로 설정함
#      - SPRING_DATASOURCE_PASSWORD=${RDS_MASTER_PASSWORD}
#      # Batch Lambda 주소
#      - BATCH_SERVICE_URL=${BATCH_SERVICE_URL}
#      # (추가) JWT 비밀키가 있다면 여기에 적기
#      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
#      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
#      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
#
#      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
#      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
#      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
#      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
#      - KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
#
#      - APP_OAUTH2_REDIRECT_URI=${APP_OAUTH2_REDIRECT_URI}
#
#      - AWS_LAMBDA_FUNCTION_NAME=${AWS_LAMBDA_FUNCTION_NAME}
#
#      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
#
#      - CLOUD_AWS_REGION_STATIC=${AWS_REGION}
#      - CLOUD_AWS_CREDENTIALS_ACCESS_KEY=${AWS_ACCESS_KEY}
#      - CLOUD_AWS_CREDENTIALS_SECRET_KEY=${AWS_SECRET_KEY}
    networks:
      - feelm-network
networks:
  feelm-network:
    driver: bridge


#   batch lambda로, db RDS로 감

#  # python
#  batch-service:
#    image: deukr/feelm-batch-service:latest
#    ports:
#      - "5000:5000"
#    depends_on:
#      - db
#    environment:
#      - TZ=Asia/Seoul
#      - DB_HOST=db  # localhost가 아니라 서비스 이름 'db'를 사용해야 함
#      - DB_PASSWORD=${DB_PASSWORD}
#      - TMDB_API_KEY=${TMDB_API_KEY}
#      - OPENAI_API_KEY=${OPENAI_API_KEY}
#
#  # DB
#  db:
#    image: mysql:8.0
#    container_name: db
#    ports:
#      - "3307:3306" # 왼쪽(내 컴퓨터 포트)만 3307로 변경
#      # Docker는 3307 포트를 쓰고 로컬에서는 3306 포트를 사용(둘다 사용하기 위해)
#    environment:
#      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#      - MYSQL_DATABASE=feelm
#      - TZ=Asia/Seoul
#    volumes:
#      - ./db_data:/var/lib/mysql # DB 데이터를 컴퓨터에 저장 (컨테이너 삭제돼도 데이터 유지)
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
